version: '3.9'

services:
  kotlinapp:
    container_name: kotlinapp
    image: francescoxx/kotlinapp:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: ${DB_URL}
        PG_USER: ${PG_USERNAME}
        PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc::postgresql://db:5432/postgres
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14.8
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}


